# Generated by Django 4.2 on 2024-09-09 19:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="user_like",
        ),
        migrations.AddField(
            model_name="product",
            name="user_likes",
            field=models.ManyToManyField(
                blank=True, related_name="product_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(default="images/no_image.png", upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="tag_name",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
